スライス

In [1]:
import numpy as np

In [5]:
X = np.random.randint(0,10,(3,3,3))
print(X)

[[[4 3 0]
  [1 0 5]
  [4 5 3]]

 [[9 6 5]
  [7 7 9]
  [3 1 2]]

 [[7 8 0]
  [5 9 7]
  [9 4 5]]]


In [14]:
#全ての行列の要素を２個飛ばしでとる．
X[: , :, 2]

array([[0, 5, 3],
       [5, 9, 2],
       [0, 7, 5]])

In [18]:
#from 0 to 1のmatrixの1行目の取得
X[0:2, 0]

array([[4, 3, 0],
       [9, 6, 5]])

In [19]:
#配列逆順
X[:,::-1]

array([[[4, 5, 3],
        [1, 0, 5],
        [4, 3, 0]],

       [[3, 1, 2],
        [7, 7, 9],
        [9, 6, 5]],

       [[9, 4, 5],
        [5, 9, 7],
        [7, 8, 0]]])

In [20]:
#全て逆順
X[::-1,::-1,::-1]

array([[[5, 4, 9],
        [7, 9, 5],
        [0, 8, 7]],

       [[2, 1, 3],
        [9, 7, 7],
        [5, 6, 9]],

       [[3, 5, 4],
        [5, 0, 1],
        [0, 3, 4]]])